### ISSUE TITLE
[BUG] Cannot access cloudfoundry request context contents due to HIL parser limitation

### ISSUE THREAD

**Issue by jameshochadel** [cloudfoundry/cloud-service-broker#1086]
## Description

Discussion in CF Slack: https://cloudfoundry.slack.com/archives/C0164KKEZGX/p1724703876380109

When referencing an element in the `request.context` map in a service definition like so:

```yaml
provision:
  computed_inputs:
    - name: space_name
      type: string
      default: ${request.context["space_name"]} # <-- here
```

I get an error: 

```
Job failed: provision could not be completed: Service broker error: 1 error(s) occurred: couldn't compute the value for "space_name", template: "${request.context[\"space_name\"]}", At column 18, line 1: map "request.context" does not have homogenous types. found TypeString and then TypeMap
```

This is due to a limitation in the HIL parser used by the broker and the structure of the `context` map. As the error suggests, the map includes values of type string and type map. [Per the OSBAPI docs](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#cloud-foundry-context-object), all values are strings except the `space_annotations` and `organization_annotations` keys, which are maps. 

Although this is a valid Go map, [the HIL parser only supports maps with homogenous types](https://github.com/hashicorp/hil/pull/11): 

> There is a restriction that map values must be homogenous in type. This is to enable the type checker to work without having to actually perform the indexing operation. This is a similar restriction to that placed on lists.

This means the `request.context` map provided by Cloud Foundry is not currently usable in the broker. 

## Expected Behavior

Brokerpak authors can use the contents of `request.context` in their service definition files. 

## Actual Behavior

Referencing keys in `request.context` causes an error at runtime. 

## Possible Fix

The simplest fix is to remove the `space_annotations` and `organization_annotations` keys from the map for contexts of type `platform: cloudfoundry` and document the limitation. This will not break compatibility for existing broker users because the feature is currently entirely broken, so it's not possible that anyone is using it. 

An alternative fix is to replace or extend the HIL parser to support maps with heterogeneous types. 

## Steps to Reproduce

See description. 

## Context

I would like to use the other values in the request context, like `space_name` and `organization_name`, to tag resources in a brokerpak. 

## Your Environment

* Version used: 2.x
* Operating System and version (desktop): Cloud Foundry, linux
* Link to your project (if public): n/a
* Platform (Azure/AWS/GCP): Any
* Applicable Services: Any

**Comment by jameshochadel** [comment]
Per the discussion in Slack, I'm submitting a PR to fix the issue by removing the keys. I created an issue so I could reference it in the code & PR.

**Comment by kanngiesser** [comment]
As a possible workaround it is possible to evaluate the context directly it your terraform files:

Service definition (excerpt)

```yml
provision:
  computed_inputs:
      - name: context
        default: ${request.context}
```

HCL (excerpt, e.g. from variables.tf)

```hcl
variable "context" {
  type        = any
  description = "cloudfoundry context object from provision call"
}

locals {
  space_name = try(var.context.space_name, "")
}
```

**Comment by kanngiesser** [comment]
Removing `request.context` will break our existing brokerpaks (!). 

We absolutely require data from the cloudfoundry context for additional context information such as org and space names. We also require data which is read from org and space annotations. It is possible to get this data with the previously described workaround.

I would propose to update the documentation instead of removing data from the context

**Comment by jameshochadel** [comment]
Hi @kanngiesser, I agree, that sounds like a better option than the proposal in my PR. I'll close the PR.

**Comment by FelisiaM** [comment]
Thank you for sharing the workaround @kanngiesser 

Since we have that and we don't have the bandwidth to make any changes at the moment I will close this bug.
