### ISSUE TITLE
[FR] Ability to update terrafomr source used by a service instance

### ISSUE THREAD

**Issue by xyloman** [cloudfoundry/cloud-service-broker#171]
This might be a misconception on my part but I recently learned that once a service is created the terraform used to create that service will be the terraform used to update it?  Therefore, how would one make use of new settings made available by the iaas provided for a service instance without creating a new instance and deleting the old?  Maybe a longer discussion is necessary to understand better the reason for this limitation and how to mitigate it.

**Comment by erniebilling** [comment]
The main reason for this limitation currently is to guarantee a match between the persisted terraform state and the terraform source. There may be extra steps required in terraform to properly handle synchronizing state before apply can be run to update a service. Investigations will be required.

**Comment by pivotal-marcela-campo** [comment]
Hi @xyloman @mogul, we recently had a conversation in [slack](https://vmware.slack.com/archives/C0164KKEZGX/p1648148068771139) around this. This is indeed work underway, there is a feature flag to enable this from v0.9.0 of the broker. Setting `BROKERPAK_UPDATES_ENABLED=true` should allow you to test this functionality and provide any feedback.

**Comment by pivotal-marcela-campo** [comment]
Hi @mogul, if you are referring to

`Service instance terraform version is upgraded to latest on update`

Then that is about upgrading the terraform binary. This is also featured flag. The feature flag for this functionality is  TERRAFORM_UPGRADES_ENABLED. We've just changed the release notes to reflect that.

The way it is implemented, the broker will first update the HCL with the latest from the brokerpak if BROKERPAK_UPDATES_ENABLED=true and then upgrade the terraform binary after that if TERRAFORM_UPGRADES_ENABLED=true

This is all work under development and as discussed you are welcome to try it out and provide feedback but it's not production ready yet.

**Comment by pivotal-marcela-campo** [comment]
Hi @mogul @xyloman,
  This feature has been out for a while now. The feature flags mentioned in the previous comment are still needed.


With BROKERPAK_UPDATES_ENABLED set to true, then updates would be performed with the latest terraform HCL in the brokerpak and the HCL stored in the database will be complete ignored.

Having TERRAFORM_UPGRADES_ENABLED set to true also provides the ablity to upgrade the terraform version. For this a `terraform_upgrade_path` has to be defined in the `manifest.yml` file as well as the list of `terraform_state_provider_replacements` and `terraform_binaries` needed to perform the upgrades. There's information on those parameters [here](https://github.com/cloudfoundry/cloud-service-broker/blob/main/docs/brokerpak-specification.md#schema) and it is probably a good idea to look into [some of our brokerpaks](https://github.com/cloudfoundry/csb-brokerpak-azure/blob/main/manifest.yml)as an example. Also, it is discourage to ship terraform upgrades alongside other changes to the HCL that are not upgrade-specific.

Do let us know if you have any feedback.
