### ISSUE TITLE
[FR] Brokerpaks should be able to include binaries beyond Terraform

### ISSUE THREAD

**Issue by mogul** [cloudfoundry/cloud-service-broker#249]
**Is your feature request related to a problem? Please describe.**
Sometimes brokerpaks need additional binaries available in the path. For example, I have an EKS brokerpak which requires the deployment include the `aws`, `kubectl`, and `helm` CLI tools. It is wrong to require that consumers of the brokerpak know about these dependencies and properly package them in their CSB deployment, much less be sure they have the right versions deployed as new versions of the brokerpak come out.

**Describe the solution you'd like**
I think a .brokerpak file should be fully self-contained, including not just the Terraform binary but any other binaries that are needed for it to operate properly.

**Describe alternatives you've considered**

I use [a script](https://github.com/GSA/datagov-ssb/blob/f240aad1668e7524e2d5ad425d7d51c7e1a07d69/app-setup-eks.sh#L34-L48) to set up the CSB deployment application before a `cf push` now. However, there's no explicit connection between the contents of this script and the requirements of the brokerpak... I have to know what utilities are needed, where to get them, which versions are supported, when to update them, etc. That responsibility should be on the brokerpak author (which happens to be me in this case, but my point is I feel bad exposing that level of responsibility to consumers of the brokerpak).

Note that while #233 removes the need to specify Terraform providers, and #231 enables inclusion of template files, I think this is a separate request, basically extending the set of binaries you can provide alongside Terraform.

**Additional Context**

My brokerpak that has these requirements is located [here](https://github.com/GSA/eks-brokerpak). Note that the tests, etc. rely on the environment to already have the CLI utils installed. That wouldn't be necessary if building the brokerpak handled this from a manifest!

**Priority**

Low

**Priority Context**

I'm able to work around it now.

**Platform** 

Any

**Applicable Services**

Any

**Comment by mogul** [comment]
That sounds great! However:
* It's not clear to me what happens with the .zip file referenced in `url_template:`... Do the contents get expanded into the PATH in the Terraform environment, or a particular subdirectory somewhere?
* If the `url_template:` includes `https://` will the build process actually retrieve the file at the link? Or is this _only_ for local files? (If it is usable for URLs generally, then I think you should continue to call it `url_template:`, but document that people should use the `file://` protocol to reference local files.)

**Comment by mogul** [comment]
Hi there... Just revisiting the need for this and wondering if anyone can answer the two questions above.

**Comment by tinygrasshopper** [comment]
Any additional binaries should be added to the brokerpak using the syntax @blgm mentioned:

```
- name: psqlcmd 
  version: 0.1.0
  source: https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
  url_template: ./tools/${name}/build/${name}_${version}_${os}_${arch}.zip
```

> Do the contents get expanded into the PATH in the Terraform environment, or a particular subdirectory somewhere?
That is right, it will be extracted into a "plugins directory" which will be available to terraform when it runs. This directory is dynamically generated, so there is no fixed path for this, but it will be added to the PATH when terraform is invoked

> https:// will the build process actually retrieve the file at the link? 
That is correct, if its a url it will be downloaded while brokerpak is being built. 

The way this works under the hood is:
- the broker would template the url with `name`, `version`, `os`, `arch` which the user can choose to use in their url
- the broker calls out call out to the [hashicorp go-getter library](https://github.com/hashicorp/go-getter/blob/7b99c311a18a8bb679bc7ff3a830a65029afef9b/get.go#L92-L106) which does the local copy or fetching from the internet 
- the dest directory of the `GetAny` is compressed as part of the brokerpak
- all binaries are made available to terraform when its serving requests from CF

**Comment by pivotal-marcela-campo** [comment]
Closing as per previous comment.
