### ISSUE TITLE
[DOCS] : Does que cloud-service-broker able to handle the orphan migration

### ISSUE THREAD

**Issue by wdesplas** [cloudfoundry/cloud-service-broker#367]
## Documentation and information request
In order to understand more specifically and move the cloud-service-broker to 2.16, I'm trying first to implement and understand the orphan migration regarding this specification:
https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md

Do we have any documentation regarding this implementation inside the cloud-service-broker or I have to start the implementation from scratch?

Thanks in advance.

Regards,

**Comment by FelisiaM** [comment]
Hi @wdesplas 

Would you mind expanding on what are you trying to achieve?

Orphan mitigation is a process that is implemented by the platform - e.g. Cloud Foundry API. The platform will send a delete request to the broker in any of the cases described [here](https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#orphan-mitigation). The broker should then treat it as any other delete request. 

Thanks,
Felisia & @jimbo459

**Comment by pivotal-marcela-campo** [comment]
Closing as there hasn't been activity in over a month.
