### ISSUE TITLE
[FR] Implement client subcommand for polling the last operation of a service-binding

### ISSUE THREAD

**Issue by mogul** [cloudfoundry/cloud-service-broker#389]
**Is your feature request related to a problem? Please describe.**

I need to know when an asynchronous binding or unbinding operation is still in progress, and what the outcome was when it finished.

**Describe the solution you'd like**

I'd like a new sub-command, `cloud-service-broker last-binding --instanceid INSTANCEID --bindingid BINDING`. The semantics should be [as described in the OSBAPI spec](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#polling-last-operation-for-service-bindings).

**Describe alternatives you've considered**

I haven't come up with a way to do this other than using raw `curl` requests.

**Additional Context**

See the link to the OSBAPI spec above.

**Priority**

Medium

**Priority Context**

It's not possible to write reliable tests without using external utilities.

**Platform** 

OSX/Linux

**Applicable Services**

N/A

**Comment by pivotal-marcela-campo** [comment]
Hi @mogul, can you provide more information on what you mean by async bindings? The broker core does not yet support async bindings, it always wait for the binding operation to complete. There is also no implementation yet for getting a binding. So the corresponding method for [OSBAPI Fetch Binding](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#fetching-a-service-binding) currently returns an error.

**Comment by mogul** [comment]
I realized that after I posted but then I forgot to close my issue. Sorry!
