### ISSUE TITLE
The terraform provider used in cloud-service-broker version 0.4.3 seems not able to handle the stderr from a comand

### ISSUE THREAD

**Issue by wdesplas** [cloudfoundry/cloud-service-broker#429]
## Description
The terraform provider used in cloud-service-broker version 0.4.3 seems not able to handle the stderr from a comand.
In fact, if an issue occurded in the module, the stderr contains a message but the cloud-service-broker stay in the "in progress" status instead of raising the error contains in the stderr output.

## Expected Behavior
The CSB must be able to raised an error once if the stderr contains an error. 

## Actual Behavior
In fact, if an issue occurded in the module, the stderr contains a message but the cloud-service-broker stay in the "in progress" status instead of raising the error contains in the stderr output.

## Steps to Reproduce
Note that the terraform-shell-resource-1.0.7 is internal.
As the insert values already exists, and no 'IGNORE' is present in the insert, the sterr will have the following error :
```
"module":"module.instance.module.registerSourceIp",
         "mode":"managed",
         "type":"null_resource",
         "name":"contents_if_missing",
         "provider":"provider.null",
         "instances":[
            {
               "schema_version":0,
               "attributes":{
                  "id":"272662459896981284",
                  "triggers":{
                     "exitstatus":"1",
                     "stderr":"ERROR 1062 (23000) at line 1: Duplicate entry '' for key 'PRIMARY'",
                     "stdout":""
                  }
               },
               "dependencies":[
                  "module.instance.module.getSourceIp.null_resource.contents",
                  "module.instance.module.getSourceIp.null_resource.contents_if_missing",
                  "module.instance.module.getSourceIp.null_resource.shell",
                  "module.instance.module.getSourceIp.random_uuid.uuid",
                  "module.instance.module.registerSourceIp.null_resource.shell",
                  "module.instance.module.registerSourceIp.random_uuid.uuid"
               ]
            }
         ]
```

Bellow the terraform content
```terraform
module "registerSourceIp" {
  source  = "http://cloud-service-broker_registry:8000/modules/matti/terraform-shell-resource/archive/v1.0.7.zip//terraform-shell-resource-1.0.7"
command = "mysql -ss -h ${var.DB_HOST} -u ${var.DB_USERNAME} --password=${var.DB_PASSWORD} -b ${var.DB_NAME} -P ${var.DB_PORT} -e \"INSERT INTO mytable(ip,service_instance_id) VALUES ${local.addIpInBddWithInstanceId};\""
  command_when_destroy = "mysql -ss -h ${var.DB_HOST} -u ${var.DB_USERNAME} --password=${var.DB_PASSWORD} -b ${var.DB_NAME} -P ${var.DB_PORT} -e \"DELETE FROM ip_iaasLegacy WHERE ip=${local.removeIpBdd} and service_instance_id='${var.instance_id}';\""
}
```

## Context
The CSB is stuck in the "in progress" state and no error is raised evenif an error is present in the stderr output.

## Your Environment

* Version used: 0.4.3
* Operating System and version (desktop): Linux
* Platform (Azure/AWS/GCP): Docker

**Comment by jimbo459** [comment]
Hi @wdesplas, thanks for reaching out. 

We are surprised to see this issue. Would you be able to try replicating this issue with the latest CSB release? In theory we have tests which should be catching this behaviour, so it's interesting to see the state you're experiencing. 

Many thanks

James

**Comment by wdesplas** [comment]
Hi, 
After investigation, using the latest version the error is raising once an error occured in teraform work properly. 

![image](https://user-images.githubusercontent.com/13151180/159666743-644c35c5-453e-4a7a-8461-04edb3a5c758.png)

I have findout that the terraform can be stuck in some case and crashed but there is not timeout raised by the csb but that's an other behaviour.

Regards,
