### ISSUE TITLE
[DOCS] : Documentation to explain the CSB feature flag needed

### ISSUE THREAD

**Issue by wdesplas** [cloudfoundry/cloud-service-broker#695]
## Documentation regarding the feature flag TERRAFORM_UPGRADES_ENABLED and BROKERPAK_UPDATES_ENABLED needed.
There is not documentation that explains how to use the feature flags TERRAFORM_UPGRADES_ENABLED and BROKERPAK_UPDATES_ENABLED. Therefore, user can note migrate properly the terraform version and the brokerpak.

In fact, it seems that not possible to do both at the same time and the content of the update will change the behaviour of the migration.
Therefore, a documentation as follow will be helpfull:

- Terraform upgrade : TERRAFORM_UPGRADES_ENABLED=true
`example of the body of the request to make an upgrade with maintenanceinfos_version`
- Brokerpak update: BROKERPAK_UPDATES_ENABLED=true
`example of the body of the request to make an upgrade`
- Serviceinstance update BROKERPAK_UPDATES_ENABLED=false and TERRAFORM_UPGRADES_ENABLED=false
`example of the body of the request to make an update`

### Limitation

- TBD

Currently I'm stuck to performe an upgrade and I'm quite sure that's only due to my miss understand feature flag usage.

This documentation be usefull for the adoption of the CSB regarding the day2 maintenance. I will be glad to do it If any references is available to test these feature.

Regards

**Comment by pivotal-marcela-campo** [comment]
Thanks @wdesplas for the feedback, we'll look into adding this documentation shortly.

**Comment by wdesplas** [comment]
Thanks @pivotal-marcela-campo , 

For information I was able to find an example in https://github.com/cloudfoundry/cloud-service-broker/blob/main/integrationtest/fixtures/terraform-upgrade-updated/manifest.yml to be able to upgrading the terraform version from 0.12.21 to 0.13.7. 

After that, I checkd the upgrade code and , was able to perform a terraform upgrade using the update api using the following body:
`curl --location --request PATCH 'https://<hostname>/v2/service_instances/<instance_id>?accepts_incomplete=true' --header 'X-Broker-API-Version: 2.13' --header 'Authorization: Basic <auth base_64>' --header 'Content-Type: application/json' 
--data-raw '{
    "service_id": "<service id>",
    "plan_id": "<plan_id>",
    "previous_values": {
        "service_id": "<service_id>",
        "plan_id": "<instance_id>",
        "maintenance_info": {
            "Version": "0.12.21"
        }
    },
    "maintenance_info": {
            "Version": "0.13.7"
    }
}'`

Regards;

**Comment by wdesplas** [comment]
Hi @pivotal-marcela-campo , 

I have test the migration of the terraform with the flag BROKERPAK_UPDATES_ENABLED enable and the decider.go does not allow the upgrade. In fact, I got the follwing error "service instance needs to be upgraded before updating"

https://github.com/cloudfoundry/cloud-service-broker/blob/main/brokerapi/broker/decider/decider.go#L60

Regards,

**Comment by pivotal-marcela-campo** [comment]
Hi @wdesplas , we do all of our testing with the two flags set to true. I don't see any reason why the `decider` could prevent such upgrade. It looks more to me like the input parameters sent on update don't match the current instance configuration. It is not allowed to send in parameters or different plan ids in the top level property and the `previous_values` section as it would require an update to the instance at the same time than the upgrade.

**Comment by wdesplas** [comment]
hi @pivotal-marcela-campo ,

My bad, I have tried to update the terraform version and the brokerpak at teh same time.

Regards,

**Comment by pivotal-marcela-campo** [comment]
Hi @wdesplas, we documented the flags and also how to[ implement an upgrade](https://github.com/cloudfoundry/cloud-service-broker/blob/main/docs/terraform-upgrades.md).  Hope this helps. Feel free to submit a PR if you see any improvements.
