### ISSUE TITLE
[FR] Support for OpenTofu(OpenTF)

### ISSUE THREAD

**Issue by norman-abramovitz** [cloudfoundry/cloud-service-broker#868]
As OpenTofu diverges from HashiCorp Terraform, it would be good to support OpenTofu to avoid HashiCorp's Licensing issue.

**Comment by pivotal-marcela-campo** [comment]
Hi @norman-abramovitz, thanks for filing this feature request. We are considering our options in the face of the HashiCorp's Licensing changes alongside with other projects of the CNCF and LF. We'll update as soon as we have a strategy in place.

**Comment by kvendingoldo** [comment]
At this moment if you need to have a support of Terraform as well as OpenTofu (and Terragrunt :) ) in one tool you can use https://github.com/tofuutils/tenv which my team wrote some months ago. A lot of users switched to that tool to unify version management in the world of Terraform. 

You're welcome to open any issues or contribute to [tenv](https://github.com/tofuutils/tenv).

**Comment by pivotal-marcela-campo** [comment]
Hi @norman-abramovitz, thanks for filing this feature request. We are considering our options in the face of the HashiCorp's Licensing changes alongside with other projects of the CNCF and LF. We'll update as soon as we have a strategy in place.
